[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  framework = "#custom"
  port = 4000
  targetPort = 3000
  autoLaunch = true

[functions]
  directory = "functions/"